apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-app3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-app3 
  name: go-app3
  namespace: go-app3-namespace
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-app3 
