apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app3
  namespace: go-app3-namespace 
  annotations:
    argocd/app-name: go-app3
    argocd/app-namespace: go-app3-namespace 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/go-app3/overlays/development
    repoURL: https://github.com/stephanie-cy/go-app3-gitops
    targetRevision: main
  destination:
    namespace: go-app3-namespace
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
