apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: go-app3
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'go-app3-namespace'
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
status: {}
